spring.application.name=fu-car-renting-system

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CarRentingSystem_DB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sa




spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect


spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html


server.port=8080